name: Gradle Package

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - docs/**
      - README.md
      - LICENSE
  push:
    tags:
      - dispatch/**
    paths-ignore:
      - docs/**
      - README.md
      - LICENSE
  # push:
  #   branches:
  #     - develop
  #   paths-ignore:
  #     - docs/**
  #     - README.md
  #     - LICENSE

jobs:
  testrun:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create local properties
        run: touch local.properties

      - name: google services json
        run: |
          touch ./app/google-services.json
          sudo chmod 777 ./app/google-services.json
          echo -e "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 -d >> ./app/google-services.json

      - name: java
        if: ${{ env.ACT }} # Only run on local act setups, as GitHub Actions provides the Android SDK on Ubuntu
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin" # See 'Supported distributions' for available options

      - name: Set up Android SDK
        if: ${{ env.ACT }} # Only run on local act setups, as GitHub Actions provides the Android SDK on Ubuntu
        uses: android-actions/setup-android@v2

      - name: Set up JDK 17
        uses: docker://gradle:8-jdk17
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Make permitted
        run: sudo chmod -R 777 ./

      - uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Test with Gradle
        run: ./gradlew testDebugUnitTest --stacktrace

      - name: Run Compile
        run: ./gradlew assembleDebug --stacktrace
