name: Gradle Package

on:
  push:
    branches:
      - develop
    paths-ignore:
      - docs/**
      - README.md
      - LICENSE

jobs:
  testrun:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create local properties
        run: touch local.properties

      - name: google services json
        run: |
          touch ./app/google-services.json
          echo -e "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 -d >> ./app/google-services.json

      - name: create local.properties
        run: |
          touch ./local.properties
          echo -e "key_alias=${{ secrets.KEYSTORE_ALIAS }}" >> ./local.properties
          echo -e "key_password=${{ secrets.KEYSTORE_PASS }}" >> ./local.properties
          echo -e "store_password=${{ secrets.KEYSTORE_PASS }}" >> ./local.properties

      - name: Set up JDK 11
        uses: docker://gradle:7.2-jdk11
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Make permitted
        run: sudo chmod -R 777 ./

      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Test with Gradle
        run: ./gradlew testDebugUnitTest --stacktrace

      - name: Run Compile
        run: ./gradlew assembleDebug --stacktrace
